onlinegym/home/urls.py
from django.urls import path
from . import views


app_name = 'home'
urlpatterns = [
    path('', views.HomeView.as_view(), name='home'),
    path('details/<int:post_id>', views.DetailsView.as_view(), name='details')
]

onlinegym/onlinegym/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static


urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('home.urls', namespace='home')),
    path('accounts/', include('accounts.urls', namespace='accounts')),
    path('coaches/', include('coaches.urls', namespace='coaches')),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

onlinegym/home/models.py
from django.db import models

# Create your models here.

onlinegym/home/views.py
from django.shortcuts import render
from django.views import View
from coaches.models import CoachPosts
from django.shortcuts import get_object_or_404


class HomeView(View):
    def get(self, request):
        coach_username = request.GET.get('coach_username')

        if coach_username:
            posts = CoachPosts.objects.filter(coach__user__username__icontains=coach_username)
        else:
            posts = CoachPosts.objects.all()
        return render(request, 'home/home.html', {'posts': posts})
    
class DetailsView(View):
    def get(self, request, post_id):
        post = get_object_or_404(CoachPosts, id=post_id)
        return render(request, "home/details.html", {'post': post})

onlinegym/home/templates/home/details.html
{% extends 'base.html' %}
{% load static %}

{% block title %}Home - OnlineGym{% endblock %}

{% block extra_css %}
{% endblock %}

{% block content %}
    <a href="{{ post.get_absolute_url }}" style="text-decoration: none;"><h5 style="font-size: large; ">{{ post.coach.user.full_name }}</h5></a>
    {% if post.image %}
        <img src="{{ post.image.url }}" class="card-img" alt="Post Image" style="max-width: 450px;">
    {% else %}
        <img src="https://via.placeholder.com/300x200" class="card-img" alt="Default Post Image">
    {% endif %}
    <h3 class="card-text">{{ post.title }}</h3>
    <p class="card-text">{{ post.content|truncatechars:100 }}</p>
    <p class="card-date">{{ post.created_at|date:"F j, Y" }}</p>
{% endblock %}

onlinegym/home/templates/home/home.html
{% extends 'base.html' %}
{% load static %}

{% block title %}Home - OnlineGym{% endblock %}

{% block extra_css %}
    <link rel="stylesheet" href="{% static 'home/home.css' %}">
{% endblock %}

{% block content %}
<div class="home-container">
    <form method="get" action="{% url 'home:home' %}" class="search-form">
        <input type="text" name="coach_username" placeholder="Search">
        <button type="submit" class="btn-search">Search</button>
    </form>

    <h2>Welcome, {{ request.user.full_name }}</h2>
    <h3>Coaches Posts</h3>
    <div class="posts-grid">
        {% for post in posts %}
            <div class="post-card">
                <a href="{% url 'home:details' post.id %}"><div class="card">
                    {% if post.image %}
                        <img src="{{ post.image.url }}" class="card-img" alt="Post Image" style="max-width: 180px;">
                    {% else %}
                        <img src="../../../media/default_profile.jpg" class="card-img" alt="Default Post Image">
                    {% endif %}
                    <div class="card-body" style="text-align: center;">
                        <a href="{{ post.get_absolute_url }}" style="text-decoration: none;"><h5 class="card-title">{{ post.coach.user.full_name }}</h5></a>
                    </div>
                </div></a>
            </div>
        {% empty %}
            <p class="no-posts">No posts yet.</p>
        {% endfor %}
    </div>
</div>
{% endblock %}