onlinegym/accounts/urls.py
from django.urls import path
from . import views


app_name = 'accounts'
urlpatterns = [
    path('userregister/', views.UserRegisterView.as_view(), name='user_register'),
    path('login/', views.UserLoginView.as_view(), name='user_login'),
    path('logout/', views.UserLogoutView.as_view(), name='user_logout'),
    path('profile/<int:user_id>/', views.UserProfileView.as_view(), name='user_profile'),
    path('profile/edit/', views.UserProfileEditView.as_view(), name='user_profile_edit'),
]

onlinegym/home/urls.py
from django.urls import path
from . import views


app_name = 'home'
urlpatterns = [
    path('', views.HomeView.as_view(), name='home'),
    path('details/<int:post_id>', views.DetailsView.as_view(), name='details')
]

onlinegym/onlinegym/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static


urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('home.urls', namespace='home')),
    path('accounts/', include('accounts.urls', namespace='accounts')),
    path('coaches/', include('coaches.urls', namespace='coaches')),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

onlinegym/accounts/models.py
from django.db import models
from django.contrib.auth.models import AbstractBaseUser
from django.core.validators import FileExtensionValidator
from phonenumber_field.modelfields import PhoneNumberField
from .managers import UserManager
from datetime import date

class User(AbstractBaseUser):
    """ manage all users """

    email = models.EmailField(unique=True)
    username = models.CharField(max_length=50, unique=True, null=True)
    full_name = models.CharField(max_length=50)
    date_of_birth = models.DateField(blank=True, null=True)
    phone_number = PhoneNumberField(unique=True, null=True)
    image = models.ImageField(
        upload_to='users/',
        validators=[FileExtensionValidator(allowed_extensions=['jpg', 'jpeg', 'png'])],
        blank=True,
        null=True,
        verbose_name="Users Image"
    )
    is_active = models.BooleanField(default=True)
    is_admin = models.BooleanField(default=False)
    is_coach = models.BooleanField(default=False)
    created = models.DateTimeField(auto_now_add=True)
    updated = models.DateTimeField(auto_now=True)

    objects = UserManager()

    USERNAME_FIELD = 'email'
    REQUIRED_FIELDS = ['username', 'full_name', 'phone_number']

    def __str__(self):
        return f"{self.full_name} - {self.email}"
    
    def has_perm(self, perm, obj=None):
        return True

    def has_module_perms(self, app_label):
        return True

    @property
    def is_staff(self):
        return self.is_admin

    def calculate_age(self):
        if self.date_of_birth:
            today = date.today()
            return today.year - self.date_of_birth.year - ((today.month, today.day) < (self.date_of_birth.month, self.date_of_birth.day))
        return None


class RegularUser(models.Model):
    """ manage regular users """
    
    user = models.OneToOneField(User, on_delete=models.CASCADE, related_name='regular_profile')
    height = models.FloatField(blank=True, null=True)
    weight = models.FloatField(blank=True, null=True)

    def __str__(self):
        return self.user.full_name

onlinegym/accounts/forms.py
from django import forms
from django.contrib.auth.forms import ReadOnlyPasswordHashField
from django.core.exceptions import ValidationError
from .models import User, RegularUser

class UniqueFieldsValidationMixin:
    def clean_email(self):
        return self.validate_unique_field('email', 'this email has already exist.')

    def clean_phone_number(self):
        return self.validate_unique_field('phone_number', 'this phone number has already exist.')

    def clean_username(self):
        return self.validate_unique_field('username', 'this username has already exist.')

    def validate_unique_field(self, field_name, error_message):
        field_value = self.cleaned_data.get(field_name)
        if User.objects.filter(**{field_name: field_value}).exists():
            raise ValidationError(error_message)
        return field_value


class UserCreationForm(forms.ModelForm, UniqueFieldsValidationMixin):
    password1 = forms.CharField(label="Password", widget=forms.PasswordInput)
    password2 = forms.CharField(label="Confirm Password", widget=forms.PasswordInput)

    class Meta:
        model = User
        fields = ['email', 'full_name']

    def clean_password2(self):
        password1 = self.cleaned_data.get('password1')
        password2 = self.cleaned_data.get('password2')
        if password1 and password2 and password1 != password2:
            raise ValidationError("passwords are not the same")
        return password2
    
    def save(self, commit=True):
        user = super().save(commit=False)
        user.set_password(self.cleaned_data['password2'])
        if commit:
            user.save()
        return user
    

class UserChangeForm(forms.ModelForm):
    password = ReadOnlyPasswordHashField(help_text='you can change password using <a href=\'../password/\'>this form</a>')

    class Meta:
        model = User
        fields = ['email', 'username', 'full_name', 'phone_number', 'password', 'image', 'is_active', 'is_admin']
        

class UserRegisterationForm(forms.Form, UniqueFieldsValidationMixin):
    email = forms.EmailField()
    phone_number = forms.CharField(max_length=11)
    full_name = forms.CharField(max_length=50)
    username = forms.CharField(max_length=50)
    image = forms.ImageField(required=False, label="Image")
    password = forms.CharField(widget=forms.PasswordInput)


class UserLoginForm(forms.Form):
    email = forms.EmailField()
    password = forms.CharField(widget=forms.PasswordInput)


class UserProfileEditForm(forms.ModelForm):
    height = forms.FloatField(required=False, label="height")
    weight = forms.FloatField(required=False, label="weight")
    
    class Meta:
        model = User
        fields = ['email', 'username', 'full_name', 'phone_number', 'date_of_birth', 'image']

    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        if hasattr(self.instance, 'regular_profile'):
            self.fields['height'].initial = self.instance.regular_profile.height
            self.fields['weight'].initial = self.instance.regular_profile.weight

    def save(self, commit=True):
        user = super().save(commit=False)
        if commit:
            user.save()
            regular_user, created = RegularUser.objects.get_or_create(user=user)
            regular_user.height = self.cleaned_data['height']
            regular_user.weight = self.cleaned_data['weight']
            regular_user.save()
        return user

onlinegym/accounts/views.py
from django.shortcuts import render, redirect, get_object_or_404
from django.views import View
from .forms import UserRegisterationForm, UserLoginForm, UserProfileEditForm
from .models import User, RegularUser
from django.contrib import messages
from django.contrib.auth import login, authenticate, logout
from django.contrib.auth.mixins import LoginRequiredMixin, AccessMixin
from coaches.forms import AppointmentForm
from coaches.models import Appointment, User, Coach, RegularUser


class UserRegisterView(View):
    """ user register view """
    
    form_class = UserRegisterationForm
    template_name = 'accounts/register.html'

    def get(self, request):
        form = self.form_class()
        return render(request, self.template_name, {'form': form})
    
    def post(self, request):
        form = self.form_class(request.POST)
        if form.is_valid():
            cd = form.cleaned_data
            user = User.objects.create(email=cd['email'], username=cd['username'], full_name=cd['full_name'], phone_number=cd['phone_number'], image=cd['image'])
            user.set_password(cd['password'])
            user.save()
            RegularUser.objects.create(user=user)
            messages.success(request, 'registered successfully', 'success')
            return redirect('home:home')
        return render(request, self.template_name, {'form': form})


class UserLoginView(View):
    """ user login view """

    form_class = UserLoginForm
    template_name = 'accounts/login.html'

    def dispatch(self, request, *args, **kwargs):
        if request.user.is_authenticated:
            messages.error(request, "you logged in before", 'error')
            return redirect("home:home")
        return super().dispatch(request, *args, **kwargs)

    def get(self, request):
        form = self.form_class()
        return render(request, self.template_name, {'form': form})

    def post(self, request):
        form = self.form_class(request.POST)
        if form.is_valid():
            email = form.cleaned_data['email']
            password = form.cleaned_data['password']
            user = authenticate(request, email=email, password=password)
            if user:
                login(request, user)
                messages.success(request, 'Logged in successfully!', 'success')
                return redirect('home:home')
            else:
                messages.error(request, 'Invalid email or password', 'danger')
        return render(request, self.template_name, {'form': form})


class UserLogoutView(LoginRequiredMixin, View):
    """ user logout view """

    def get(self, request):
        logout(request)
        messages.success(request, 'Logged out successfully!', 'success')
        return redirect('home:home')


class UserProfileView(LoginRequiredMixin, View):
    """ show user profile and send plan request for coach """

    form_class = AppointmentForm
    template_name = 'accounts/profile.html'

    def get(self, request, user_id):
        user = get_object_or_404(User, id=user_id)            
        form = self.form_class()
        return render(request, self.template_name, {'user': user, 'form': form})
    
    def post(self, request, user_id):
        form = self.form_class(request.POST, request.FILES)
        if form.is_valid():
            appointment = form.save(commit=False)
            user = get_object_or_404(RegularUser, user=request.user)
            coach_user = get_object_or_404(User, id=user_id)
            coach = get_object_or_404(Coach, user=coach_user)
            appointment.user = user
            appointment.coach = coach
            appointment.save()
            messages.success(request, 'Appointment sent successfully', 'success')
            return redirect('accounts:user_profile', user_id=user_id)
        return render(request, 'accounts/profile.html', {'form': form})
        

class UserProfileEditView(LoginRequiredMixin, View):
    """ for editing the user information """

    form_class = UserProfileEditForm
    template_name = 'accounts/editprofile.html'

    def get(self, request):
        form = self.form_class(instance=request.user)
        return render(request, self.template_name, {'form': form})
    
    def post(self, request):
        form = self.form_class(request.POST, request.FILES, instance=request.user)
        if form.is_valid():
            form.save()
            messages.success(request, 'Profile editted successfully', 'success')
            return redirect('accounts:user_profile', user_id=request.user.id)
        return render(request, self.template_name, {'form': form})

onlinegym/accounts/templates/accounts/editprofile.html
{% extends 'base.html' %}
{% load static %}

{% block title %} Edit profile{% endblock %}

{% block extra_css %}
    <link rel="stylesheet" href="{% static 'accounts/editprofile.css' %}">
{% endblock %}

{% block content %}
<div class="edit-profile-container">
    <h2> Edit Profile</h2>
    <form method="post" enctype="multipart/form-data" class="profile-edit-form">
        {% csrf_token %}
        
        <div class="form-group profile-image-upload">
            <label for="id_image">
                {% if form.instance.image %}
                    <img src="{{ form.instance.image.url }}" alt="profile picture" class="current-profile-image">
                {% else %}
                    <img src="{% static 'accounts/images/default-profile.png' %}" alt="default picture " class="current-profile-image">
                {% endif %}
                <span class="change-image-text">Change picture </span>
            </label>
            {{ form.image }}
        </div>
        
        <div class="form-group">
            <label for="id_username">Username</label>
            {{ form.username }}
        </div>
        
        <div class="form-group">
            <label for="id_full_name">Full name </label>
            {{ form.full_name }}
        </div>
        
        <div class="form-group">
            <label for="id_email">Email</label>
            {{ form.email }}
        </div>
        
        <div class="form-group">
            <label for="id_phone_number">Phone number </label>
            {{ form.phone_number }}
        </div>
        
        <div class="form-group">
            <label for="id_date_of_birth">Birthday date</label>
            {{ form.date_of_birth }}
        </div>
        
        <div class="form-group">
            <label for="id_height">height</label>
            {{ form.height }}
        </div>
        
        <div class="form-group">
            <label for="id_weight">weight</label>
            {{ form.weight }}
        </div>
        
        <div class="form-actions">
            <button type="submit" class="save-btn">Edit</button>
            <a href="{% url 'accounts:user_profile' user_id=request.user.id %}" class="cancel-btn">Cancel</a>
        </div>
    </form>
</div>
{% endblock %}

onlinegym/accounts/templates/accounts/login.html
{% extends 'base.html' %}
{% load static %}

{% block title %}Login{% endblock %}

{% block extra_css %}
    <link rel="stylesheet" href="{% static 'accounts/login.css' %}">
{% endblock %}

{% block content %}
<div class="login-container">
    <h2>Login</h2>
    <form method="post" class="login-form">
        {% csrf_token %}
        {{ form.as_p }}
        <button type="submit" class="btn-login">Login</button>
    </form>
    <p class="register-link">No accounts?<a href="{% url 'accounts:user_register' %}">Register</a></p>
</div>
{% endblock %}

onlinegym/accounts/templates/accounts/profile.html
{% extends 'base.html' %}
{% load static %}

{% block title %}User Profile{% endblock %}

{% block extra_css %}
    <link rel="stylesheet" href="{% static 'accounts/profile.css' %}">
{% endblock %}

{% block content %}
<div class="profile-container">
    <h2>User Profile</h2>
    <div class="profile-info">
        <div class="profile-image">
            {% if user.image %}
                <img src="{{ user.image.url }}" alt="Profile Picture" style="max-width: 150px;">
            {% else %}
                <img src="../../../media/default_profile.jpg" alt="Default Profile">
            {% endif %}
        </div>
        <div class="profile-details">
            <p><strong>Full Name:</strong> {{ user.full_name }}</p>
            <p><strong>Email:</strong> {{ user.email }}</p>
            <p><strong>Username:</strong> {{ user.username }}</p>
            <p><strong>Phone Number:</strong> {{ user.phone_number }}</p>
            {% if user.is_coach %}
                <p><strong>Specialty:</strong> {{ user.coach_profile.specialty }}</p>
                <p><strong>Certifications:</strong> {{ user.coach_profile.certifications }}</p>
            {% else %}
                <p><strong>Date of Birth:</strong> {{ user.date_of_birth }}</p>
                <p><strong>Height:</strong> {{ user.regular_profile.height }} cm</p>
                <p><strong>Weight:</strong> {{ user.regular_profile.weight }} kg</p>
            {% endif %}
        </div>
    </div>
</div>
{% if user.id != request.user.id %}
<div class="form-container">
    <form action="" method="post" enctype="multipart/form-data">
        {% csrf_token %}
        {{ form.as_p }}
        <input type="submit" value="Send">
    </form>
</div>
{% endif %}
<a href="{% url 'home:home' %}" class="btn-back">Back to Home</a>
{% if request.user == user %}
    <a href="{% url 'accounts:user_profile_edit' %}" class="btn-back">Edit Profile</a>
{% endif %}

{% endblock %}

onlinegym/accounts/templates/accounts/register.html
{% extends 'base.html' %}
{% load static %}

{% block title %}Register{% endblock %}

{% block extra_css %}
    <link rel="stylesheet" href="{% static 'accounts/register.css' %}">
{% endblock %}

{% block content %}
<div class="register-container">
    <h2>Register</h2>
    <form method="post" class="register-form" enctype="multipart/form-data">
        {% csrf_token %}
        {{ form.as_p }}
        <button type="submit" class="btn-register">Register</button>
    </form>
    <p class="login-link">account?<a href="{% url 'accounts:user_login' %}">Login</a></p>
</div>
{% endblock %}